const unit3Deck = [

  {
    "tag": "3.1",
    "question": "Long Answer: Explain the single-layer DWH architecture in full — its purpose, why it is considered a virtual DWH structure, its drawbacks in terms of performance and reporting, and the type of business for which it is and is not suitable.",
    "answer": "A single-layer DWH architecture aims to minimize the amount of data stored by removing redundancy, creating a dense dataset. Its major drawback is that transactional and analytical processing are not separated: OLTP systems gathering detailed raw data from day-to-day business processes are conjoined with OLAP applications supporting data analytics, trend analysis, data mining, and reporting. It is the most basic DWH design and excludes a staging area. It is fundamentally a virtual DWH structure, since the multidimensional view of the organization's operational data is created by means of middleware. Consequently, query processing speeds can be slow, and DWH queries can adversely affect transactional workloads in the operational systems. Query results may also be 'messy,' as non-required operational data can be included, reporting capabilities may be inadequate, and flexibility and analytical capabilities are limited. It is suitable for a business where all the raw operational data are in a standardized format, which does not require complex analytics, and where BI is not used systematically — but it is not suitable for large organizations and businesses with complex data requirements or several data streams."
  },
  {
    "tag": "3.2",
    "question": "Long Answer: Explain the two-layer DWH architecture in full — how it separates the DWH from source systems, its four data flow stages, the role of the staging area and data mart level, and its advantages and limitations compared to the single-layer architecture.",
    "answer": "A two-layer DWH architecture separates the DWH layer from the source systems, with the separation being physical, using two servers (a system server and a database server). It entails four data flow stages: (1) the source layer, (2) data staging, (3) the DWH, and (4) a layer that enables analysis. It includes a staging area between the source systems and DWH applications to cleanse and transform the data prior to loading it into the DWH, plus a discrete layer that facilitates analytical processing. A data mart level can also be added between the DWH and the BI applications, giving departmental access to domain-specific information and enhancing overall DWH security. Compared to the single-layer architecture, the two-layer DWH stores, organizes, and manages data more efficiently. However, it is still not very expandable, cannot effectively scale to accommodate organizational growth, and cannot support many users."
  },
  {
    "tag": "3.3",
    "question": "Long Answer: Explain the three-layer DWH architecture in full — what it typically contains, the purpose of each of its three tiers (bottom, middle, top), how OLAP/ROLAP/MOLAP fit into the middle tier, what Kimball et al. call the 'presentation server,' and why this architecture suits large organizations.",
    "answer": "The three-layer DWH architecture typically contains multiple source systems, a reconciled layer, and a DWH system that includes data marts and a multi-dimensional DWH layer using OLAP cubes. It entails a bottom, middle, and top tier. The bottom tier encompasses a relational database system with data cleansed, transformed, and loaded into a staging area, with transformation and integration executed according to the reconciled layer, providing relational storage and management. The middle tier is an abstracted view of the analytical database in the form of an OLAP server, hosting data marts and facilitating the 'slicing' and 'dicing' of data; it can be implemented via ROLAP, where an extended RDBMS maps functions on multidimensional data to standard relational operations, or MOLAP, where multidimensional processes run on a dedicated multidimensional OLAP server. Kimball et al. (2008) refer to the bottom and middle tiers collectively as the 'presentation server,' a single source for analytic data queried directly by business users, reporting systems, and BI applications. The top tier is the client-facing front-end layer, where tools such as BI applications, dashboards, query tools, analysis tools, reporting tools, and data mining tools are used to interact with the DWH; these tools must be correct, perform well, be easy to use, and be aesthetically pleasing. Because the data flow from raw operational data to business insights is well-defined and organized, but more complex and expensive to implement, this architecture is usually reserved for large and complex organizations."
  }
]
