const unit1Deck = [

  {
    "tag": "1.1",
    "question": "What is big data, as defined in the coursebook, and why is it difficult to manage?",
    "answer": "Big data refers to datasets that are extremely large, complex, and diverse. It entails data that inundate organizations daily. Big data grow exponentially over time. Hence, they are difficult to analyze, manage, and maintain."
  },
  {
    "tag": "1.1",
    "question": "List and define the five characteristics of big data (Gordon, 2014).",
    "answer": "Volume: the amount of data to store and analyze is so large that it requires special considerations. Variety: the data consist of multiple types of data and/or data from multiple sources; structured, semi-structured, and unstructured forms must be considered. Velocity: new data are produced rapidly, so operating on 'old' (stale) data will not be sufficiently valuable. Value: the data have a perceived or quantifiable benefit for an organization. Veracity: the data's correctness (and truthfulness) can be assessed."
  },
  {
    "tag": "1.1",
    "question": "MCQ: Which characteristic of big data refers to the amount of data being so large that it requires special considerations? A) Variety B) Volume C) Value D) Veracity",
    "answer": "B) Volume — the amount of data to store and analyze is so large that it requires special considerations."
  },
  {
    "tag": "1.1",
    "question": "MCQ: Which characteristic refers to data consisting of multiple types and/or coming from multiple sources, requiring structured, semi-structured, and unstructured forms to be considered? A) Velocity B) Veracity C) Variety D) Volume",
    "answer": "C) Variety — the data consist of multiple types of data and/or data from multiple sources."
  },
  {
    "tag": "1.1",
    "question": "MCQ: Which characteristic describes that new data are produced rapidly, so operating on stale data is not sufficiently valuable? A) Value B) Velocity C) Veracity D) Volume",
    "answer": "B) Velocity — new data are produced rapidly; thus, operating on 'old' (stale) data will not be sufficiently valuable."
  },
  {
    "tag": "1.1",
    "question": "MCQ: Which characteristic refers to data having a perceived or quantifiable benefit for an organization? A) Veracity B) Variety C) Value D) Volume",
    "answer": "C) Value — the data have a perceived or quantifiable benefit for an organization."
  },
  {
    "tag": "1.1",
    "question": "MCQ: Which characteristic relates to assessing the correctness and truthfulness of the data? A) Veracity B) Velocity C) Value D) Volume",
    "answer": "A) Veracity — the data's correctness (and truthfulness) can be assessed."
  },
  {
    "tag": "1.1",
    "question": "Define structured data, give its typical example, and describe how it is stored.",
    "answer": "Structured data entails data that are organized into a formatted repository. A 'traditional' relational standard query language (SQL) database is a typical example. The format is predictable since patterns occur regularly. Structured data records are stored in tables made up of rows and columns, and the tables contain attributes, keys, and indexes. Structured data are associated with well-defined metadata to ensure they can be effectively analyzed and managed."
  },
  {
    "tag": "1.1",
    "question": "MCQ: Structured data records are typically stored in which format? A) Key-value pairs B) Tables made up of rows and columns C) Graph nodes and edges D) Free-text documents",
    "answer": "B) Tables made up of rows and columns, containing attributes, keys, and indexes."
  },
  {
    "tag": "1.1",
    "question": "Why are RDBMSs, despite easily managing structured data, not suitable for managing big data in general?",
    "answer": "Structured data are associated with well-defined metadata, so they can be easily managed by an RDBMS. However, SQL-based relational databases do not scale easily and, as a result, have difficulty dealing with data that increase rapidly in quantity, such as in the case of big data. Consequently, RDBMSs are not suitable for the management of big data."
  },
  {
    "tag": "1.1",
    "question": "Define semi-structured data and give the coursebook's example.",
    "answer": "Semi-structured data exhibit some form of structure, even though the data do not necessarily explicitly conform to a data model. The coursebook's example is an email: the message content consists of structureless text, but the email contains a structure with a sender, recipient, subject, message header, and message. Semi-structured data are described as repetitive unstructured data — the repetition occurs many times, often in the same structure and/or embodiment."
  },
  {
    "tag": "1.1",
    "question": "List the examples of semi-structured data sources and file formats given in the coursebook.",
    "answer": "Examples include computer-generated reports and files generated by machine interactions, such as the metering of a consumer's energy usage. Typical file formats are XML (eXtensible Markup Language), JSON (JavaScript Object Notation), and CSV (comma-separated values)."
  },
  {
    "tag": "1.1",
    "question": "MCQ: Which file formats does the coursebook give as typically containing semi-structured data? A) .docx and .pdf B) XML, JSON, and CSV C) MP4 and JPEG D) SQL tables",
    "answer": "B) XML, JSON, and CSV."
  },
  {
    "tag": "1.1",
    "question": "Describe what the CSV and JSON figure examples in Section 1.1 represent.",
    "answer": "The CSV file example shows the country names and sales territories of customers, identifiable through a customer ID. The JSON file example gives the details of a customer associated with an order; the order's details are not included in that file, but it is associated through the order number to another file."
  },
  {
    "tag": "1.1",
    "question": "Define unstructured data and explain why it is described as difficult, or 'clumsy,' to access.",
    "answer": "Unstructured data records differ substantially from each other — neither the form nor the content are repeated regularly. They are the most difficult data type to work with and manage, as they are not organized in any predefined manner and do not conform to a predefined data model. Unstructured data are unpredictable and, since they do not contain a structure, are essentially unrecognizable by a computer. Hence, they are rather 'clumsy' to access, and long strings of data must be sequentially searched (and parsed) to find a specific unit of data."
  },
  {
    "tag": "1.1",
    "question": "List the examples of unstructured data formats and sources given in the coursebook.",
    "answer": "Examples include PDF and Word documents, images, texts, media logs, audio and/or video files, and photographs. A recording of call center conversations is given as an example that can provide rich organizational insights. Data gathered by the Internet of Things (IoT) and social media are also given as forms of unstructured data."
  },
  {
    "tag": "1.1",
    "question": "MCQ: Which of the following is an example of unstructured data given in the coursebook? A) A CSV file of customer sales territories B) A relational database table C) A recording of a call center conversation D) An email's sender and subject fields",
    "answer": "C) A recording of a call center conversation."
  },
  {
    "tag": "1.1",
    "question": "Explain the role metadata plays in distinguishing semi-structured data from unstructured data.",
    "answer": "Metadata (e.g., tags and elements) are used to group and store semi-structured data, giving it organizational properties that make it easier to manage and analyze than unstructured data. Unfortunately, the metadata of unstructured data is inadequate, in the sense that it cannot be used to easily automate and manage the data by means of a conventional RDBMS."
  },
  {
    "tag": "1.1",
    "question": "Give the coursebook's exact definitions of: standard query language, repository, metadata, XML, and JSON.",
    "answer": "Standard query language: a language used to manipulate and retrieve data from relational databases. Repository: a managed directory for storing and describing digital objects for a digital archive. Metadata: information that defines and describes the structure of data to ease the manipulation thereof. XML (eXtensible Markup Language): a markup language and file format used to store, transmit, and reconstruct arbitrary data, based on a set of rules to encode data in a format readable by both humans and machines. JSON (JavaScript Object Notation): an open standard useful to exchange data; it contains text that is easily readable to store and transmit data objects, consisting of values that are serializable."
  },
  {
    "tag": "1.1",
    "question": "Long Answer: Give a complete account of Section 1.1. Define big data; define and explain all five characteristics of big data; and define each of the three data classifications (structured, semi-structured, unstructured), giving the defining features and at least one coursebook example of each.",
    "answer": "Big data refers to datasets that are extremely large, complex, and diverse; they inundate organizations daily and grow exponentially over time, which is why they are difficult to analyze, manage, and maintain. Big data encompass five characteristics (Gordon, 2014): volume (the amount of data to store and analyze is so large that it requires special considerations), variety (the data consist of multiple types of data and/or data from multiple sources, so structured, semi-structured, and unstructured forms must be considered), velocity (new data are produced rapidly, so operating on stale data is not sufficiently valuable), value (the data have a perceived or quantifiable benefit for an organization), and veracity (the data's correctness and truthfulness can be assessed).\n\nBig data are classified as structured, semi-structured, and unstructured. Structured data are organized into a formatted repository; a traditional relational SQL database is the typical example. The format is predictable since patterns occur regularly, and records are stored in tables made up of rows and columns containing attributes, keys, and indexes. Structured data have well-defined metadata, so they are easily managed by an RDBMS — though RDBMSs do not scale easily and are therefore not suitable for managing big data in general.\n\nSemi-structured data exhibit some form of structure but do not necessarily explicitly conform to a data model. The coursebook's example is an email: the message content is structureless text, but the email itself has structure — a sender, recipient, subject, message header, and message. Semi-structured data are described as repetitive unstructured data, since the same structure or embodiment repeats many times. Examples include computer-generated reports and machine-interaction files such as energy meter readings, typically in XML, JSON, or CSV format. The coursebook illustrates this with a CSV file of customer countries and sales territories identified by customer ID, and a JSON file of customer details linked to an order via an order number. Metadata such as tags and elements help group and store semi-structured data, making it easier to manage than unstructured data, though this metadata remains inadequate for full automation by a conventional RDBMS.\n\nUnstructured data records differ substantially from each other; neither their form nor content repeats regularly. They are the most difficult data type to manage, since they are not organized in any predefined manner and do not conform to a predefined data model. This makes them unpredictable and essentially unrecognizable by a computer, so they are 'clumsy' to access — long strings of data must be sequentially searched and parsed to find a specific unit of data. Examples include PDF and Word documents, images, texts, media logs, audio and/or video files, photographs, recordings of call center conversations, and data gathered by the Internet of Things (IoT) and social media."
  }
]
